#2.
a=open("a2.txt","r+")
a.write("Writing with r+")
print(a.read())
a=open("a2.txt","w+")
a.write("Overwriting with w+\n")
print(a.read())
a=open("a2.txt","a+")
a.write("Writing with a+\n")
print(a.read())
